version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: supersecret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
    - ./pgadmin:/var/lib/pgadmin
    networks:
      - my_network
    depends_on:
      - db

networks:
  my_network:
    driver: bridge